version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo



# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8085:8085
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     volumes:
#       - ./data:/data/db




# version: '3'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8085:8085
#     environment:
#       - NODE_ENV=development
#     depends_on:
#       - mongo
#   mongo:
#     image: mongo
#     volumes:
#       - ./data:/data/db


